### ISSUE TITLE
Practica6

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-ka194#1]
[PRACTICA6_plataforma de la agricultura inteligente .pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-ka194/files/13221981/PRACTICA6_plataforma.de.la.agricultura.inteligente.pdf)

**Comment by irving1989** [comment]
Portada: 22 puntos.
Procedimiento: 25 puntos.
Figuras, ilustraciones y fotografías: 22 puntos. Cuentan con más del mínimo de ilustraciones requeridas, pero no cuentan con su respectiva descripción.
Resultados y conclusiones: 20 puntos. Falto describir los resultados.
Total: 89 puntos

Porcentaje obtenido: 26.7/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
