### ISSUE TITLE
Práctica DRS

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-ka194#2]
[DRS practica 6.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-ka194/files/13349295/DRS.practica.6.pdf)

**Comment by irving1989** [comment]
Portada: 25 puntos.
Procedimiento: 25 puntos.
Figuras, ilustraciones y fotografías: 25 puntos.
Resultados y conclusiones: 25 puntos.
Total: 100 puntos

Porcentaje obtenido: 30/30

**Comment by josealfredo79** [comment]
Tiene detalles favor de checar bien..por favor..bien hecho...
